name: "MagicMirror"
description: "MagicMirror as Homeassistant addon"
version: "1.5.9"
slug: "magicmirror"
init: false
options:
  command: ""
schema:
  command: "str?"
arch:
  - amd64
ports:
  8080/tcp: 8080
map:
  - share:rw
